package com.lbxy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImage<M extends BaseImage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setLocation(java.lang.String location) {
		set("location", location);
		return (M)this;
	}
	
	public java.lang.String getLocation() {
		return getStr("location");
	}

	public M setContentId(java.lang.Long contentId) {
		set("contentId", contentId);
		return (M)this;
	}
	
	public java.lang.Long getContentId() {
		return getLong("contentId");
	}

}
