package com.lbxy.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setOpenId(java.lang.String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	public M setSessionKey(java.lang.String sessionKey) {
		set("sessionKey", sessionKey);
		return (M)this;
	}
	
	public java.lang.String getSessionKey() {
		return getStr("sessionKey");
	}

	public M setPhoneNumber(java.lang.String phoneNumber) {
		set("phoneNumber", phoneNumber);
		return (M)this;
	}
	
	public java.lang.String getPhoneNumber() {
		return getStr("phoneNumber");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
		return (M)this;
	}
	
	public java.math.BigDecimal getBalance() {
		return get("balance");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setIdNoPic(java.lang.String idNoPic) {
		set("idNoPic", idNoPic);
		return (M)this;
	}
	
	public java.lang.String getIdNoPic() {
		return getStr("idNoPic");
	}

	public M setStuNoPic(java.lang.String stuNoPic) {
		set("stuNoPic", stuNoPic);
		return (M)this;
	}
	
	public java.lang.String getStuNoPic() {
		return getStr("stuNoPic");
	}

	public M setRealName(java.lang.String realName) {
		set("realName", realName);
		return (M)this;
	}
	
	public java.lang.String getRealName() {
		return getStr("realName");
	}

	public M setAvatarUrl(java.lang.String avatarUrl) {
		set("avatarUrl", avatarUrl);
		return (M)this;
	}
	
	public java.lang.String getAvatarUrl() {
		return getStr("avatarUrl");
	}

	public M setGender(java.lang.Integer gender) {
		set("gender", gender);
		return (M)this;
	}
	
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	public M setStudentNumber(java.lang.String studentNumber) {
		set("studentNumber", studentNumber);
		return (M)this;
	}
	
	public java.lang.String getStudentNumber() {
		return getStr("studentNumber");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

}
