package com.lbxy.model;

import com.lbxy.model.base.BaseBill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bill extends BaseBill<Bill> {
	public static final Bill DAO = new Bill().dao();

	@Override
	protected void filter(int filterBy) {
		if (filterBy == FILTER_BY_UPDATE) {

		}
	}
}
