package com.lbxy.model;

import com.lbxy.model.base.BaseFlea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Flea extends BaseFlea<Flea> {
	public static final Flea dao = new Flea().dao();
}
