package com.lbxy.model;

import com.lbxy.model.base.BaseLostfound;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lostfound extends BaseLostfound<Lostfound> {
	public static final Lostfound DAO = new Lostfound().dao();
}
