package com.lbxy.model;


import com.lbxy.model.base.BaseNotification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Notification extends BaseNotification<Notification> {
	public static final Notification dao = new Notification().dao();
}
