package com.lbxy.model;

import com.lbxy.model.base.BaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	public static final Order DAO = new Order().dao();
}
