package com.lbxy.model;

import com.lbxy.model.base.BaseTreehole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Treehole extends BaseTreehole<Treehole> {
	public static final Treehole DAO = new Treehole().dao();
}
