package com.lbxy.model;

import com.lbxy.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User DAO = new User().dao();
}
